[build-system]
build-backend = "hatchling.build"
requires = [
    "hatchling",
    "hatch-vcs",
    "semiwrap",
    "hatch-meson",
    "hatch-robotpy",
    "hatch-nativelib",
    "wpilib==2027.0.0a7",
    "robotpy-fields==2027.0.0a7",
]


[project]
name = "gtsam-apriltag"
dynamic = ["version"]
description = "GTSAM based AprilTag localisation for RobotPy"
license = "BSD-3-Clause"
dependencies = [
    "wpilib==2027.0.0a7",
]

[[project.authors]]
name = "FRC Team 4774 and 1880"
email = "enquiries@thedropbears.org.au"

[project.urls]
"Source code" = "https://github.com/thedropbears/gtsam-apriltag"


[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "gtsam_apriltag/version.py"

[tool.hatch.build.targets.wheel]
packages = ["gtsam_apriltag"]

#[[tool.hatch.build.hooks.robotpy.maven_lib_download]]
#artifact_id = "gtsam-cpp"
#group_id = "release.org.wpilib.thirdparty.gtsam"
#repo_url = "https://frcmaven.wpi.edu"
#version = "2027-4.3-7"
#staticlibs = [
#  "cephes-gtsamRelWithDebInfo",
#  "gtsam_unstableRelWithDebInfo",
#  "gtsamRelWithDebInfo",
#  "metis-gtsamRelWithDebInfo",
#]
#extract_to = "gtsam"


[tool.hatch.build.hooks.semiwrap]

[tool.hatch.build.hooks.meson]


[tool.semiwrap]
update_init = ["gtsam_apriltag gtsam_apriltag._estimator"]
#scan_headers_ignore = []

[tool.semiwrap.name_transform]
default = "snake_case"
enum_value = "CAPS_CASE"
known_words = []

[tool.semiwrap.extension_modules."gtsam_apriltag._estimator"]
name = "estimator"

depends = [
    "wpilib",
    "wpimath",
    "fields",
]

includes = [
    "gtsam/include",
]

[tool.semiwrap.extension_modules."gtsam_apriltag._estimator".headers]
estimator = "include/estimator.hpp"
